apiVersion: v1
kind: Service
metadata:
  name: plataforma-civica-backend
  labels:
    app: plataforma-civica-backend
spec:
  type: ClusterIP
  selector:
    app: plataforma-civica-backend
  ports:
    - name: http
      port: 3333
      targetPort: 3333
