apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plataforma-civica-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/eps-fcte-2025-2/plataforma-civica-frontend:latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
spec:
  project: default
  source:
    repoURL: "https://github.com/eps-fcte-2025-2/continuous-deployment.git"
    path: "plataforma-civica/frontend"
    targetRevision: main
    kustomize: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plataforma-civica
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
