apiVersion: apps/v1
kind: Deployment
metadata:
  name: plataforma-civica-frontend
  namespace: plataforma-civica
  labels:
    app: plataforma-civica-frontend
spec:
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
  selector:
    matchLabels:
      app: plataforma-civica-frontend
  template:
    metadata:
      labels:
        app: plataforma-civica-frontend
    spec:
      volumes:
        - name: envfile
          emptyDir: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: frontend
      initContainers:
        - name: write-env
          image: busybox:1.36
          command: ["/bin/sh", "-lc"]
          args:
            - |
              env > /env/.env
          envFrom:
            - configMapRef:
                name: plataforma-civica-frontend-config
          volumeMounts:
            - name: envfile
              mountPath: /env

      containers:
        - name: frontend
          image: ghcr.io/eps-fcte-2025-2/plataforma-civica-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: plataforma-civica-frontend-config
          volumeMounts:
            - name: envfile
              mountPath: /app/.env
              subPath: .env

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
