apiVersion: apps/v1
kind: Deployment
metadata:
  name: plataforma-civica-frontend
  labels:
    app: plataforma-civica-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plataforma-civica-frontend
  template:
    metadata:
      labels:
        app: plataforma-civica-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/eps-fcte-2025-2/plataforma-civica-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: plataforma-civica-frontend-config

          # startupProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3000
          #   periodSeconds: 5
          #   failureThreshold: 12

          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3000
          #   periodSeconds: 10
          #   timeoutSeconds: 2
          #   failureThreshold: 3

          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3000
          #   periodSeconds: 30
          #   timeoutSeconds: 3
          #   failureThreshold: 3

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"