apiVersion: v1
kind: Service
metadata:
  name: plataforma-civica-frontend
  labels:
    app: plataforma-civica-frontend
spec:
  type: ClusterIP
  selector:
    app: plataforma-civica-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
