apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.25.0
    releaseName: cnpg
    namespace: cnpg

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
  - target:
      kind: ConfigMap
      name: cnpg-grafana-dashboard
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
